### ISSUE TITLE
Hamming exercise, add test case for empty strand

### ISSUE THREAD

**Issue by aarti** [exercism/xlua#26]
1. Add a test case for comparing in the case one strand is empty 
2. Try to also test for the case that teaches the concept "Lua array index starts at 1"

**Comment by ryanplusplus** [comment]
The empty strand case was added here: https://github.com/exercism/xlua/commit/9a1a44cc839c45ea768c4c9c0017d751ceea6d58

Interestingly, the example incorrectly starts indexing at 0. See #72 for a fix.

I think this should be closed unless someone has a solution for enforcing array indexing at 1. For Hamming it will be difficult because `nil == nil`.

**Comment by ryanplusplus** [comment]
Closing for now

**Comment by kytrinyx** [comment]
+1 :) Thanks!
